language: node_js
node_js:
  - "node"

jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage